spring:
  application:
    name: icebreak
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_directory
    username: postgres
    password: password
  # Entity ??? ??? ???? ??? ?? / ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true